using System.Text.Json;
using Lodestar.Text.Similarity;
using Xunit;

namespace Lodestar.Text.Tests.Similarity;

/// <summary>The second permutation family, against the same reference's current default.</summary>
/// <remarks>
/// <c>datasketch</c> 2.0.0 named three schemes and made <c>affine32</c> the default, so the block
/// these tests read is what a caller comparing against a current reference gets from the call the
/// suite beside this one makes against <c>legacy</c>. Compared <strong>exactly</strong>, for the
/// reason that file gives: a signature is a list of hashes, and a tolerance would mean the
/// algorithm had diverged rather than the arithmetic (#645).
/// </remarks>
public sealed class Affine32SchemeOracleTests
{
    private static readonly JsonDocument Corpus = Load();

    private static JsonDocument Load()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "oracles", "text_similarity.json");
        return JsonDocument.Parse(File.ReadAllText(path));
    }

    private static JsonElement Block => Corpus.RootElement.GetProperty("affine32");

    private static ulong[] Coefficients(string name) =>
        [.. Block.GetProperty(name).EnumerateArray().Select(value => value.GetUInt64())];

    private static MinHashPermutations Permutations() =>
        new(Coefficients("multipliers"), Coefficients("addends"), MinHashScheme.Affine32);

    private static IReadOnlyList<JsonElement> LegacyCases =>
        [.. Corpus.RootElement.GetProperty("cases").EnumerateArray()];

    /// <summary>The documents live in the legacy block; only the signatures differ per scheme.</summary>
    private static string[] Tokens(string key) =>
        [.. LegacyCases.First(document => document.GetProperty("key").GetString() == key)
            .GetProperty("tokens").EnumerateArray().Select(token => token.GetString()!)];

    public static TheoryData<string> Keys()
    {
        var data = new TheoryData<string>();
        foreach (JsonElement document in Block.GetProperty("cases").EnumerateArray())
        {
            data.Add(document.GetProperty("key").GetString()!);
        }

        return data;
    }

    private static JsonElement Case(string key) =>
        Block.GetProperty("cases").EnumerateArray()
            .First(document => document.GetProperty("key").GetString() == key);

    [Theory]
    [MemberData(nameof(Keys))]
    public void Every_affine32_signature_matches_datasketch(string key)
    {
        uint[] expected = [.. Case(key).GetProperty("signature")
            .EnumerateArray().Select(value => value.GetUInt32())];

        uint[] actual = new MinHash(Permutations()).Signature(Tokens(key));

        Assert.Equal(expected, actual);
    }

    [Fact]
    public void The_corpus_carries_the_variant_it_was_generated_under()
    {
        Assert.Equal(
            "MinHash(seed=1, sha1_hash32, scheme=affine32)",
            Block.GetProperty("variant").GetString());
    }

    /// <summary>The two schemes are different families, not two spellings of one.</summary>
    /// <remarks>
    /// Worth asserting rather than assuming: if a future change made the affine branch fall
    /// through to the legacy arithmetic, every test above would still pass against a corpus
    /// regenerated by the same mistake. This one compares the two schemes to each other, which
    /// no regeneration can reconcile.
    /// </remarks>
    [Fact]
    public void Affine32_and_legacy_do_not_agree_on_a_single_document()
    {
        string key = Block.GetProperty("cases").EnumerateArray()
            .First().GetProperty("key").GetString()!;

        uint[] affine = new MinHash(Permutations()).Signature(Tokens(key));
        ulong[] legacyA = [.. Corpus.RootElement.GetProperty("multipliers")
            .EnumerateArray().Select(value => value.GetUInt64())];
        ulong[] legacyB = [.. Corpus.RootElement.GetProperty("addends")
            .EnumerateArray().Select(value => value.GetUInt64())];
        uint[] legacy = new MinHash(new MinHashPermutations(legacyA, legacyB)).Signature(Tokens(key));

        Assert.Equal(affine.Length, legacy.Length);
        Assert.NotEqual(affine, legacy);
    }

    [Fact]
    public void Legacy_is_what_a_caller_naming_no_scheme_gets()
    {
        var permutations = new MinHashPermutations([1UL, 3UL], [0UL, 1UL]);

        Assert.Equal(MinHashScheme.Legacy, permutations.Scheme);
    }
}
