#!/usr/bin/env python3
"""Read every ADR's declared relationships and cross them into one index (#630).

An ADR is immutable -- `tools/check_adr_immutable.py` refuses a diff that touches
one -- so an amended decision cannot be edited to name its amendment. Seventeen
records declare `amends` or `supersedes`, onto fifteen distinct decisions, and not
one of those fifteen points forward; `0082`'s Consequences section says so in as
many words. A reader who cites `0101` without reaching `0103` states the opposite
of what this repository decided.

This module is the half both the generator and the two guards share: the reader
for an ADR's frontmatter, and the crossing that turns the forward edges every
record declares into the reverse edges no record can.

Three relations, because two of them are routinely confused:

  supersedes  the named decision no longer holds, in whole or in the part named
  amends      the named decision still holds, changed where this one says
  applies     the named decision is unchanged and used again, on a rule it
              already stated -- `0097` of `0095`: "This record does not amend
              0095 so much as apply it"

`applies` is not decoration. `0095` published four members and wrote that
publishing later is always available; `0097` and `0098` exercise that sentence
rather than changing it, and a reader told they *amended* 0095 would go looking
for a clause that moved. The index carries both, apart.

Standard library only, and an emitter rather than PyYAML. `.githooks/pre-commit`
runs the guards through whichever of `python3` or `python` a contributor's machine
resolves, not through `.venv-oracles`, so an import outside the standard library
turns a missing package into a failed commit. Nothing here parses arbitrary YAML
either: the frontmatter is a fixed four-key block and anything else is a finding,
which is `tools/check_adr_frontmatter.py`'s whole subject.

Every four-digit reference is quoted, in the frontmatter and in the index. PyYAML
reads YAML 1.1, where a bare `0010` is octal and resolves to the integer 8 -- so
an unquoted key would collide `0010` with `0008` for any reader that does use a
YAML library.
"""

from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
DECISIONS = ROOT / "docs" / "decisions"
INDEX = DECISIONS / "index.yaml"

# `0001-target-framework.md`, which is every ADR and not README.md.
ADR_FILE = re.compile(r"^(\d{4})-.+\.md$")

# The declared relations, in the order they are written and emitted.
FORWARD = ("supersedes", "amends", "applies")
# The reverse of each, computed here and never written by hand.
REVERSE = {"supersedes": "superseded_by", "amends": "amended_by", "applies": "applied_by"}

# The block's delimiters, found by string search rather than by a pattern: a lazy
# `.*?` across newlines backtracks, and this is a fence, not a grammar.
FENCE = "---\n"
QUOTED = re.compile(r'"(\d{4})"')
# A frontmatter key, which is the whole of what one may look like.
KEY = re.compile(r"\A[a-z_]+\Z")
# The title's one source of truth and the status the frontmatter repeats, both read
# line by line: a run of blanks in front of `(.+)` is S8786's ambiguity.
HEADING = "# "
HEADING_SEPARATOR = " — "
STATUS_PREFIX = "**Status:**"

# Prose, commented at emit time rather than here: a block of `#` lines in this
# file reads to tools/check_comment_length.py as a comment, which it is not.
HEADER_PROSE = (
    "docs/decisions/index.yaml -- generated by tools/regen_adr_index.py, never edited.",
    "",
    "One entry per record in docs/decisions/, keyed by its number. `supersedes`,",
    "`amends` and `applies` are what the record's own frontmatter declares;",
    "`superseded_by`, `amended_by` and `applied_by` are those edges reversed, which",
    "is the direction an immutable record cannot carry for itself.",
    "",
    "Before citing a decision, follow its reverse edges: `amended_by` says the",
    "decision changed, `applied_by` says it was used again unchanged. An empty list",
    "means nothing was declared, never that nothing exists -- the reading lives in",
    "docs/decisions/README.md's relationships column.",
    "",
    "tools/check_adr_index_sync.py refuses any drift between this file and the",
    "records it is generated from.",
)

KEY_NUMBER = "number"
KEY_STATUS = "status"
KEY_TITLE = "title"


class AdrError(Exception):
    """A record this module cannot read, reported rather than guessed at."""


def adr_paths(directory: pathlib.Path | None = None) -> list[pathlib.Path]:
    """Every ADR file, in number order."""
    where = DECISIONS if directory is None else directory
    return sorted(path for path in where.glob("*.md") if ADR_FILE.match(path.name))


def number_of(path: pathlib.Path) -> str:
    """`0095-the-numerical-layer.md` -> `0095`."""
    match = ADR_FILE.match(path.name)
    if match is None:
        raise AdrError(f"{path.name} is not an ADR file name")
    return match.group(1)


def split_frontmatter(text: str) -> tuple[str | None, str]:
    """The frontmatter block and the body below it, or (None, text) when there is none."""
    if not text.startswith(FENCE):
        return None, text
    end = text.find(f"\n{FENCE}", len(FENCE) - 1)
    if end < 0:
        return None, text
    return text[len(FENCE):end + 1], text[end + 1 + len(FENCE):]


def read_frontmatter(block: str) -> dict[str, object]:
    """The fixed four-key block, as `{"status": str, "amends": [...], ...}`.

    A strict reader for one shape rather than a YAML implementation: a key per
    line, `status` a bare word, the three relations a flow sequence of quoted
    four-digit numbers. Anything else raises, because a frontmatter this cannot
    read is a frontmatter nobody should trust -- and the guard that reports it
    reads better than a silent default.
    """
    found: dict[str, object] = {}
    for line in block.splitlines():
        if not line.strip():
            continue
        key, separator, raw = line.partition(":")
        if not separator or KEY.match(key) is None:
            raise AdrError(f"cannot read frontmatter line {line!r}")
        if key in found:
            raise AdrError(f"frontmatter declares {key!r} twice")
        if key in FORWARD:
            found[key] = read_list(key, raw.strip())
        else:
            found[key] = unquote(raw.strip())
    return found


def unquote(raw: str) -> str:
    """A scalar with or without its quotes, so one spelling is not a finding."""
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
        return raw[1:-1]
    return raw


def read_list(key: str, raw: str) -> list[str]:
    """`["0095", "0097"]` -> `["0095", "0097"]`, and `[]` -> `[]`."""
    if not (raw.startswith("[") and raw.endswith("]")):
        raise AdrError(f"{key}: {raw!r} is not a `[...]` list of quoted numbers")
    inner = raw[1:-1].strip()
    numbers = QUOTED.findall(inner)
    if inner and not numbers:
        raise AdrError(f"{key}: {raw!r} holds no quoted four-digit number")
    rebuilt = ", ".join(f'"{number}"' for number in numbers)
    if inner and inner != rebuilt:
        raise AdrError(f"{key}: {raw!r} should read [{rebuilt}]")
    return numbers


def title_of(number: str, text: str) -> str:
    """The title from the record's own `# NNNN — Title` heading."""
    for line in text.splitlines():
        if not line.startswith(HEADING):
            continue
        found, separator, title = line[len(HEADING):].partition(HEADING_SEPARATOR)
        if separator and found.strip() == number and title.strip():
            return title.strip()
    raise AdrError(f"{number}: no `{HEADING}{number}{HEADING_SEPARATOR}<title>` heading")


def status_line_of(text: str) -> str | None:
    """The record's `**Status:**` text, which the frontmatter's `status` opens."""
    for line in text.splitlines():
        if line.startswith(STATUS_PREFIX):
            return line[len(STATUS_PREFIX):].strip() or None
    return None


def read_record(path: pathlib.Path) -> dict[str, object]:
    """One ADR, as everything the index and the guards need from it."""
    number = number_of(path)
    text = path.read_text(encoding="utf-8")
    block, body = split_frontmatter(text)
    record: dict[str, object] = {
        KEY_NUMBER: number,
        "path": path,
        KEY_TITLE: title_of(number, body),
        "status_line": status_line_of(body),
        "frontmatter": None if block is None else read_frontmatter(block),
    }
    return record


def read_all(directory: pathlib.Path | None = None) -> list[dict[str, object]]:
    """Every ADR, in number order."""
    return [read_record(path) for path in adr_paths(directory)]


def build(records: list[dict[str, object]]) -> dict[str, dict[str, object]]:
    """The index: each record's declared edges, plus every edge that names it.

    A relation onto a number no record carries is dropped from the reverse pass
    and left in the forward list, where `check_adr_frontmatter.py` reports it. The
    index says what the records say; it is not the place a dangling reference is
    argued about.
    """
    entries = {str(record[KEY_NUMBER]): declared(record) for record in records}
    reverse_edges(entries)
    return entries


def declared(record: dict[str, object]) -> dict[str, object]:
    """One record's own entry: what it says, with its reverse edges still empty."""
    frontmatter = record["frontmatter"] or {}
    entry: dict[str, object] = {
        KEY_TITLE: record[KEY_TITLE],
        KEY_STATUS: frontmatter.get(KEY_STATUS, "") or "",
    }
    for relation in FORWARD:
        entry[relation] = list(frontmatter.get(relation, []) or [])
    for reverse in REVERSE.values():
        entry[reverse] = []
    return entry


def reverse_edges(entries: dict[str, dict[str, object]]) -> None:
    """Fill each entry's reverse edges from every entry that names it."""
    for number, entry in entries.items():
        for relation, reverse in REVERSE.items():
            for target in entry[relation]:
                if target in entries:
                    entries[target][reverse].append(number)

    for entry in entries.values():
        for reverse in REVERSE.values():
            entry[reverse] = sorted(set(entry[reverse]))


def quote(value: str) -> str:
    """A double-quoted YAML scalar, because a title may hold a colon or a `#`."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def emit(entries: dict[str, dict[str, object]]) -> str:
    """The index file's whole text, byte for byte what the guard compares against."""
    lines = [f"# {prose}".rstrip() for prose in HEADER_PROSE]
    lines.append("")
    for number in sorted(entries):
        entry = entries[number]
        lines.append(f"{quote(number)}:")
        lines.append(f"  {KEY_TITLE}: {quote(str(entry[KEY_TITLE]))}")
        lines.append(f"  {KEY_STATUS}: {quote(str(entry[KEY_STATUS]))}")
        for key in (*FORWARD, *REVERSE.values()):
            numbers = ", ".join(quote(value) for value in entry[key])
            lines.append(f"  {key}: [{numbers}]")
        lines.append("")
    return "\n".join(lines)


def generate(directory: pathlib.Path | None = None) -> str:
    """Read the records and emit the index, which is the whole pipeline."""
    return emit(build(read_all(directory)))
