#!/usr/bin/env python3
"""Turn the C# fences in the guides into a project the compiler can judge.

The guides are the single source of truth: nothing here copies a snippet, so a
snippet and its compiled counterpart cannot drift. Each ```csharp fence becomes
one method, which is what lets two snippets in the same guide both declare `cv`
without colliding. `using` lines are hoisted to the top of the generated file, so
a fence inherits the namespaces an earlier fence in the same guide opened --
exactly the way a reader reads the page.

Symbols the prose introduces without showing them (`trainingDocuments`,
`corpusVectors`, ...) come from the hand-written partial classes in
samples/Lodestar.DocSnippets/SnippetContext.cs. That file is scaffolding, not a
copy of any snippet.

A fence that genuinely cannot compile opts out with an HTML comment on the line
before it:

    <!-- docs-compile: skip - reason a reviewer can disagree with -->

A marker that is not followed by a fence is an error: an opt-out that stopped
applying must not go unnoticed.

Pages under docs/reference/ carry three more markers, and land in the
Lodestar.DocSnippets.Reference namespace instead of Lodestar.DocSnippets:

    <!-- docs-declaration -->                a signature above a fence, excluded
                                               from compilation entirely
    <!-- docs-run: skip - reason -->          compiles, but is never executed
    int d = Levenshtein.Distance("a", "b");  // => 1

A trailing `// =>` comment on a local-variable declaration becomes an
assertion on the value the declaration promises; a plain `//` stays a comment
untouched, on a reference page or a guide alike.

Usage:
    python3 tools/extract_doc_snippets.py [--check]

--check reports what it would generate and writes nothing.
"""

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = REPO / "samples" / "Lodestar.DocSnippets" / "Generated"
SOURCES = ["README.md", "src/*/README.md", "docs/guides/*.md",
           "docs/reference/*/*.md", "docs/reference/*/*/*.md"]

REFERENCE = "docs/reference"

FENCE = re.compile(r"^```csharp[ \t]*\n(.*?)^```[ \t]*$", re.S | re.M)

# A trailing comment ("using Lodestar.Text;  // TextElement") must not stop
# the line being recognised as a directive to hoist.
USING = re.compile(r"^using +[A-Za-z_][A-Za-z0-9_.]* *; *(//.*)?$")

# Bounded by the literal "-->", not "\s*": a lazy quantifier between two
# optional-whitespace groups is super-linear on backtracking; trim in Python instead.
SKIP = re.compile(r"^<!--\s*docs-compile:\s*skip\b(?P<reason>.*?)-->\s*$")
REASON_SEPARATORS = " \t-—:"

# The value a reader is promised. Bound to a local first, so the assertion names
# something: an expression statement would have to be re-evaluated to be checked.
ARROW = re.compile(r"^(?P<code>[^;]*;)\s*//\s*=>(?P<expected>.+)$")
DECLARATION = re.compile(r"^<!--\s*docs-declaration\s*-->\s*$")
RUN_SKIP = re.compile(r"^<!--\s*docs-run:\s*skip\b(?P<reason>.*?)-->\s*$")

# `var d = ...;` or `int d = ...;` -- the shapes an assertion can name.
BINDING = re.compile(r"^\s*(?:[\w.<>\[\],?]+\s+)+(?P<name>[A-Za-z_]\w*)\s*=")

FENCE_OPEN = "```csharp"

HEADER = """// <auto-generated />
//
// Extracted from {source} by tools/extract_doc_snippets.py.
// Do not edit: edit the Markdown. This file is regenerated and git-ignored.
"""


def class_name(path: pathlib.Path) -> str:
    """A C# identifier from the path: docs/reference/text/distances.md -> TextDistances.

    Two areas may share a file name -- persistence.md exists for more than one
    package -- so a reference page's identifier carries its directory. Guides keep
    the stem alone, so their generated file names do not churn.
    """
    relative = path.relative_to(REPO).as_posix()
    parts = relative[len(REFERENCE) + 1:-3].split("/") if relative.startswith(REFERENCE) else [path.stem]
    words = [word for part in parts for word in part.replace("_", "-").split("-") if word]
    return "".join(word[:1].upper() + word[1:] for word in words)


def is_reference(path: pathlib.Path) -> bool:
    return path.relative_to(REPO).as_posix().startswith(REFERENCE)


def sources() -> list[pathlib.Path]:
    found: list[pathlib.Path] = []
    for pattern in SOURCES:
        if "*" in pattern:
            found.extend(sorted(REPO.glob(pattern)))
        else:
            found.append(REPO / pattern)
    return found


def line_of(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def marker_above(text: str, fence_start: int) -> tuple[str, str] | None:
    """The marker on the line immediately above the fence: its kind and its reason."""
    preceding = text[:fence_start].rstrip("\n").rsplit("\n", 1)
    line = preceding[-1].strip() if preceding else ""
    for kind, pattern in (("skip", SKIP), ("run-skip", RUN_SKIP)):
        match = pattern.match(line)
        if match is not None:
            return kind, match.group("reason").strip(REASON_SEPARATORS) or "no reason given"
    if DECLARATION.match(line):
        return "declaration", ""
    return None


def assert_lines(body: list[str], origin: str, start_line: int) -> list[str]:
    """Every `// =>` comment, as the assertion it promises."""
    out: list[str] = []
    for offset, source_line in enumerate(body):
        match = ARROW.match(source_line)
        if match is None:
            out.append(source_line)
            continue
        binding = BINDING.match(match.group("code"))
        if binding is None:
            # arrow_failures has already written the sentence this contributor needs;
            # asserting on a name that is not there would replace it with a traceback.
            out.append(source_line)
            continue
        out.append(match.group("code"))
        out.append(
            f'SnippetAssert.Value({binding.group("name")}, "{match.group("expected").strip()}", '
            f'"{origin}:{start_line + offset}");'
        )
    return out


def arrow_failures(path: pathlib.Path, text: str) -> list[str]:
    """`// =>` comments this file carries that name no local to assert."""
    relative = path.relative_to(REPO).as_posix()
    failures = []
    for number, source_line in enumerate(text.splitlines(), start=1):
        match = ARROW.match(source_line)
        if match is not None and BINDING.match(match.group("code")) is None:
            failures.append(
                f"{relative}:{number}: a '// =>' comment on a line that binds nothing. "
                "Assign the value to a local first, so the assertion has a name to check."
            )
    return failures


def orphan_markers(text: str) -> list[int]:
    """Lines carrying an opt-out marker that no C# fence follows."""
    lines = text.splitlines()
    return [
        number
        for number, line in enumerate(lines, start=1)
        if SKIP.match(line.strip()) and lines[number:number + 1] != [FENCE_OPEN]
    ]


def hoist_usings(snippet: str, usings: list[str]) -> list[str]:
    """The snippet's lines, with its `using` directives moved into `usings`."""
    body: list[str] = []
    for source_line in snippet.splitlines():
        if USING.match(source_line):
            if source_line.strip() not in usings:
                usings.append(source_line.strip())
        else:
            body.append(source_line)

    while body and not body[0].strip():
        body.pop(0)
    while body and not body[-1].strip():
        body.pop()
    return body


def method(index: int, origin: str, body: list[str], skip_run: str | None) -> str:
    """One fence, as a method — which is what keeps two fences' locals apart."""
    indented = "\n".join(f"        {line}" if line.strip() else "" for line in body)
    attribute = f'    [SnippetSkipRun("{skip_run}")]\n' if skip_run is not None else ""
    return (
        f"    /// <summary>The C# fence at {origin}.</summary>\n"
        f"{attribute}"
        f"    public void Snippet{index}()\n    {{\n{indented}\n    }}\n"
    )


def compilation_unit(path: pathlib.Path, usings: list[str], methods: list[str], reference: bool) -> str:
    """The generated file: hoisted usings, then one partial class of methods."""
    text = HEADER.format(source=path.relative_to(REPO).as_posix())
    text += "\n" + "\n".join(sorted(usings)) + "\n" if usings else "\n"
    namespace = "Lodestar.DocSnippets.Reference" if reference else "Lodestar.DocSnippets"
    text += f"\nnamespace {namespace};\n\ninternal sealed partial class {class_name(path)}\n{{\n"
    return text + "\n".join(methods) + "}\n"


def render(path: pathlib.Path, text: str) -> tuple[str, int, list[tuple[int, str]]]:
    """The compilation unit for one Markdown file, and the fences that opted out."""
    usings: list[str] = []
    methods: list[str] = []
    skipped: list[tuple[int, str]] = []
    relative = path.relative_to(REPO).as_posix()
    reference = is_reference(path)

    for index, match in enumerate(FENCE.finditer(text)):
        line = line_of(text, match.start())
        marker = marker_above(text, match.start())
        kind = marker[0] if marker else None
        if kind in ("skip", "declaration"):
            skipped.append((line, marker[1] or "a declaration, not a snippet"))
            continue
        body = hoist_usings(match.group(1), usings)
        if reference:
            body = assert_lines(body, relative, line + 1)
        methods.append(method(index, f"{relative}:{line}", body, marker[1] if kind == "run-skip" else None))

    if not methods:
        return "", 0, skipped
    return compilation_unit(path, usings, methods, reference), len(methods), skipped


def scan(path: pathlib.Path) -> tuple[str, int, list[tuple[str, int, str]], list[str]]:
    """Everything one Markdown file contributes: its file, its counts, its complaints."""
    relative = path.relative_to(REPO).as_posix()
    if not path.exists():
        return "", 0, [], [f"{relative}: listed in SOURCES but missing"]

    text = path.read_text(encoding="utf-8")
    failures = [
        f"{relative}:{line}: a 'docs-compile: skip' marker that no {FENCE_OPEN} fence "
        "follows. Remove it, or move it back above its fence."
        for line in orphan_markers(text)
    ] + arrow_failures(path, text)
    document, compiled, opted_out = render(path, text)
    return document, compiled, [(relative, line, reason) for line, reason in opted_out], failures


def clear_output() -> None:
    """Generated files are rebuilt every run, so a deleted fence cannot linger."""
    if OUTPUT.exists():
        for stale in OUTPUT.glob("*.cs"):
            stale.unlink()
    OUTPUT.mkdir(parents=True, exist_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report without writing")
    arguments = parser.parse_args()

    if not arguments.check:
        clear_output()

    failures: list[str] = []
    skipped: list[tuple[str, int, str]] = []
    compiled = 0
    written = 0

    for path in sources():
        document, count, opted_out, complaints = scan(path)
        compiled += count
        skipped.extend(opted_out)
        failures.extend(complaints)
        if document and not arguments.check:
            (OUTPUT / f"{class_name(path)}.g.cs").write_text(document, encoding="utf-8")
            written += 1

    print(f"snippets compiled : {compiled}")
    print(f"snippets opted out: {len(skipped)}")
    for source, line, reason in skipped:
        print(f"  {source}:{line} — {reason}")
    if not arguments.check:
        print(f"files written     : {written} in {OUTPUT.relative_to(REPO)}")

    for failure in failures:
        print(f"::error::{failure}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
