"""Regenerate src/Lodestar.Text/Vectorization/StopWords.Snowball.cs.

Downloads the Snowball stop-word lists, checks each file against the SHA-256
pinned below, and emits the C# source. The lists are BSD-3-Clause (see
docs/decisions/0002-provenance-and-the-allowed-references.md); nothing here touches the
nltk stopwords corpus, whose terms are unclarified.

    python tools/fetch_stopwords.py            # regenerate
    python tools/fetch_stopwords.py --check    # verify the checked-in file is current

A checksum mismatch means Snowball edited the list upstream. That is a decision
to make, not a failure to paper over: read the diff, update the pin here, adjust
the counts in StopWordsTests, and record it.
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys
import urllib.request

URL = "https://snowballstem.org/algorithms/{lang}/stop.txt"

# Retrieved 2026-08-05.
PINNED_SHA256 = {
    "french": "e235f5e633bf831c601ce6f1dc87d8608c038209a7aab64e69a9e70f52f83d4c",
    "german": "22a7785b53860256280fba74b93d8f09a0f3a8f52edaa3cdc3750e8c13a3874c",
    "italian": "054a4926bcdf85fd016bd2a3647f0ef90c7498ddc3d69e165751fba86c4c026a",
    "portuguese": "be242d802beb0d1868589409dd998d33b45873ef36f2b9f582dd0cf9099e1ae7",
    "spanish": "042669c6c97605f5e57278b67474c65d58d628a59a004e618a0ac06bc2d38222",
}

PROPERTY = {
    "french": ("French", "fr"),
    "german": ("German", "de"),
    "italian": ("Italian", "it"),
    "portuguese": ("Portuguese", "pt"),
    "spanish": ("Spanish", "es"),
}

OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "src/Lodestar.Text/Vectorization/StopWords.Snowball.cs"

HEADER = """// long-comment: BSD-3-Clause requires the copyright notice to travel with
//     the data it covers; NOTICE and THIRD-PARTY-NOTICES.md carry the same text.
// <auto-generated>
//     Generated by tools/fetch_stopwords.py from the Snowball stop-word lists,
//     pinned by SHA-256 in that script. Do not edit by hand: rerun it.
//
//     Copyright (c) 2001, Dr Martin Porter
//     Copyright (c) 2002, Richard Boulton
//     BSD-3-Clause. See docs/decisions/0002-provenance-and-the-allowed-references.md.
// </auto-generated>

namespace Lodestar.Text.Vectorization;

public static partial class StopWords
{
    // One nested type per language, as StopWords.cs gives English: reading
    // Italian never builds the other four.

"""


def fetch(lang: str) -> str:
    with urllib.request.urlopen(URL.format(lang=lang), timeout=30) as response:
        raw = response.read()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != PINNED_SHA256[lang]:
        raise SystemExit(
            f"{lang}: SHA-256 mismatch\n  expected {PINNED_SHA256[lang]}\n  got      {digest}\n"
            "The upstream list changed. See the module docstring."
        )
    return raw.decode("utf-8")


def parse(text: str) -> list[str]:
    """One stop word per line, at the start; comments begin with a vertical bar."""
    words = []
    for line in text.splitlines():
        word = line.split("|")[0].strip()
        if word:
            words.append(word)
    if len(words) != len(set(words)):
        raise SystemExit("duplicate entry in the source list")
    return words


def emit(lang: str, words: list[str]) -> str:
    name, code = PROPERTY[lang]
    lines = [
        f"    /// <summary>The Snowball {name} stop-word list ({len(words)} words, <c>{code}</c>).</summary>",
        f"    public static IReadOnlyCollection<string> {name} => {name}List.Value;",
        "",
        f"    private static class {name}List",
        "    {",
        "        internal static readonly IReadOnlyCollection<string> Value = StopWordSet.Freeze(",
        "        [",
    ]
    for start in range(0, len(words), 10):
        chunk = ", ".join(f'"{w}"' for w in words[start:start + 10])
        lines.append(f"            {chunk},")
    lines.append("        ]);")
    lines.append("    }")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the checked-in file is out of date")
    args = parser.parse_args()

    blocks = []
    for lang in PINNED_SHA256:
        words = parse(fetch(lang))
        print(f"{lang}: {len(words)} words", file=sys.stderr)
        blocks.append(emit(lang, words))

    generated = HEADER + "\n\n".join(blocks) + "\n}\n"

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8")
        if current != generated:
            print(f"{OUTPUT} is out of date; rerun without --check", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is up to date", file=sys.stderr)
        return 0

    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
