#!/usr/bin/env python3
"""Generate the .globalconfig that raises the Sonar rules the analyzer package ships disabled.

SonarAnalyzer.CSharp enables a subset of its own rules by default; the SonarCloud
quality profile enables a different set. Rules in the second and not the first are
invisible to `dotnet build` and blocking at the quality gate, which is a three-minute
round trip per finding (issue #109).

Two inputs, both cheap:

  * the profile's active rules, from one anonymous SonarCloud call -- the project is
    public, so no token is involved and anyone who clones this repository can run it;
  * `runs[].tool.driver.rules[]` of a SARIF v2 error log, where the compiler itself
    declares which rules are enabled by default.

The intersection is written as severity entries. `warning`, not `error`:
TreatWarningsAsErrors already decides whether a finding stops the build, and one
lever for that decision is enough.

The tool takes no path or URL on its command line: one job, one repository, and
an input it cannot be pointed at is an input nobody can point at something else
(issue #131 -- a SonarCloud taint-analysis scan of this script's four argparse
values, all of which reached a path or URL sink, produced five findings that
neither the issues API nor the web UI would name). The SARIF error log, the
`.globalconfig` output and the SonarCloud API base are now fixed constants
derived from `ROOT` or declared alongside it; `--check` is the only flag left.
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

DEFAULT_API = "https://sonarcloud.io/api"
ORGANIZATION = "cyrilb1531"
PROJECT = "CyrilB1531_data.net"
LANGUAGE = "cs"
REPOSITORY = "csharpsquid"

RULE_ID = re.compile(r"^S\d+$")
EXIT_DRIFT = 1
EXIT_UNREACHABLE = 2
EXIT_INPUT_MISSING = 3
EXIT_TRUNCATED = 4

ROOT = Path(__file__).resolve().parent.parent
ERROR_LOG = ROOT / "obj" / "sonar-rules.sarif"
OUTPUT = ROOT / ".globalconfig"


def fetch(url: str) -> dict:
    """One GET, or a clean failure naming the URL."""
    with urllib.request.urlopen(url, timeout=30) as response:  # noqa: S310 - fixed https host
        return json.loads(response.read().decode("utf-8"))


def profile_key(api: str) -> str:
    """The C# profile associated with *this project*, not the organization's default."""
    url = f"{api}/qualityprofiles/search?organization={ORGANIZATION}&project={PROJECT}"
    for profile in fetch(url)["profiles"]:
        if profile["language"] == LANGUAGE:
            return profile["key"]
    raise LookupError(f"no {LANGUAGE} quality profile is associated with {PROJECT}")


class TruncatedResponse(RuntimeError):
    """rules/search reported more rules than the page it sent back."""


def active_rules(payload: dict) -> set[str]:
    """The rule ids the profile activates, without the repository prefix."""
    total, rules = payload["total"], payload["rules"]
    if total > len(rules):
        raise TruncatedResponse(
            f"rules/search reports total={total} but this response carries only "
            f"{len(rules)} rules: the page (ps={payload.get('ps', '?')}) is smaller than "
            "the profile. Raise ps past the profile size or paginate with p=2, 3, ... "
            "-- the intersection below would otherwise silently drop the rules that fell "
            "off the page, and a build enforcing less than the quality gate is exactly "
            "the failure this generator exists to prevent."
        )
    return {
        key.split(":", 1)[1]
        for key in (rule["key"] for rule in rules)
        if key.startswith(f"{REPOSITORY}:")
    }


def disabled_rules(error_log: Path) -> set[str]:
    """The rule ids the analyzer package declares and ships disabled."""
    # utf-8-sig: the compiler writes a byte-order mark.
    document = json.loads(error_log.read_text(encoding="utf-8-sig"))
    disabled: set[str] = set()
    for run in document["runs"]:
        for rule in run["tool"]["driver"].get("rules", []):
            enabled = rule.get("defaultConfiguration", {}).get("enabled")
            if enabled is False and RULE_ID.match(rule["id"]):
                disabled.add(rule["id"])
    return disabled


def delta(active: set[str], disabled: set[str]) -> list[str]:
    """Active on the server and disabled in the package, in rule-number order."""
    return sorted(active & disabled, key=lambda rule: int(rule[1:]))


def render(rules: list[str], profile_key: str, analyzer_version: str) -> str:
    """The file, deterministic and timestamp-free so it can be drift-checked."""
    lines = [
        "is_global = true",
        "",
        "# Generated by tools/generate_sonar_globalconfig.py -- do not edit by hand.",
        "#",
        f"# The rules SonarCloud's profile {profile_key} activates for {PROJECT} and that",
        f"# SonarAnalyzer.CSharp {analyzer_version} ships disabled, so that a finding fails the",
        "# build on the machine that wrote the code rather than the quality gate three",
        "# minutes after the push. See CLAUDE.md's analyzer section and",
        "# issue #109.",
        "#",
        "# warning, not error: TreatWarningsAsErrors in the root Directory.Build.props is",
        "# what turns a finding into a failure, and two levers for one decision is one too",
        "# many.",
        "",
    ]
    lines += [f"dotnet_diagnostic.{rule}.severity = warning" for rule in rules]
    return "\n".join(lines) + "\n"


def analyzer_version() -> str:
    """The pin the root Directory.Build.props carries, quoted in the header."""
    text = (ROOT / "Directory.Build.props").read_text(encoding="utf-8")
    match = re.search(r"<LodestarSonarAnalyzerVersion>([^<]+)</", text)
    if match is None:
        raise LookupError("Directory.Build.props declares no LodestarSonarAnalyzerVersion")
    return match.group(1)


def build() -> tuple[str, str]:
    key = profile_key(DEFAULT_API)
    payload = fetch(
        f"{DEFAULT_API}/rules/search?organization={ORGANIZATION}&qprofile={key}"
        f"&activation=true&languages={LANGUAGE}&ps=500")
    rules = delta(active_rules(payload), disabled_rules(ERROR_LOG))
    return render(rules, key, analyzer_version()), key


def main(argv: list[str] | None = None) -> int:
    """Build the file (or check it), and give each failure its own exit code.

    The two ``except`` clauses below both catch ``OSError``-family errors and
    must not confuse one for the other. ``urllib.error.HTTPError`` -- raised
    for a SonarCloud 5xx or 404 -- is itself a ``urllib.error.URLError``
    subclass, and it sets ``.filename`` to the request URL with ``.strerror``
    left ``None``. Catching ``OSError`` first would route a status error into
    "cannot read <url>: None" at ``EXIT_INPUT_MISSING``, treating a live
    network failure as a local one. Catching ``URLError`` first (with the
    bare ``TimeoutError`` urlopen does not always wrap in it) keeps every
    network failure at ``EXIT_UNREACHABLE``, and only a genuinely local
    ``ERROR_LOG`` problem falls through to ``EXIT_INPUT_MISSING``.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare instead of writing")
    args = parser.parse_args(argv)

    try:
        expected, key = build()
    except TruncatedResponse as error:
        print(str(error), file=sys.stderr)
        return EXIT_TRUNCATED
    except (urllib.error.URLError, TimeoutError) as error:
        # Order matters: see this function's docstring for why URLError is
        # caught ahead of OSError.
        print(f"could not reach {DEFAULT_API}: {error}", file=sys.stderr)
        return EXIT_UNREACHABLE
    except OSError as error:
        # Reached only for a local ERROR_LOG problem -- see this function's
        # docstring for why this is never a URLError.
        print(f"cannot read {error.filename}: {error.strerror}", file=sys.stderr)
        return EXIT_INPUT_MISSING

    target = OUTPUT
    if not args.check:
        target.write_text(expected, encoding="utf-8")
        print(f"{target}: {expected.count('dotnet_diagnostic.')} rules from profile {key}")
        return 0

    actual = target.read_text(encoding="utf-8") if target.exists() else ""
    if actual == expected:
        print(f"{target} matches profile {key}")
        return 0
    print("".join(difflib.unified_diff(
        actual.splitlines(keepends=True), expected.splitlines(keepends=True),
        fromfile=str(target), tofile="regenerated")))
    return EXIT_DRIFT


if __name__ == "__main__":
    sys.exit(main())
